### ISSUE TITLE
how to contribute?

### ISSUE THREAD

**Issue by mrsauravsahu** [shubhamzanwar/flippie#1]
How can I contribute to this project.

**Comment by shubhamzanwar** [comment]
It's still in its early stages. I'll add contributing guidelines soon. (maybe after the first animation component is released)

Thanks for your interest, Sahu! 🤘🏽

**Comment by mrsauravsahu** [comment]
Thanks @shubhamzanwar

**Comment by shubhamzanwar** [comment]
@mrsauravsahu I've added the contributing guidelines [here](https://github.com/shubhamzanwar/flippie/blob/master/.github/CONTRIBUTING.md)

I've also collated the issues for the project on this [board](https://github.com/shubhamzanwar/flippie/projects/1)

If you'd like to contribute in anyway, happy to add you as a contributor.

**Comment by mrsauravsahu** [comment]
A-OK 👌
