### ISSUE TITLE
Add slide up card component

### ISSUE THREAD

**Issue by shubhamzanwar** [shubhamzanwar/flippie#5]
![image](https://user-images.githubusercontent.com/15626155/77220640-3b119400-6b68-11ea-8d37-968cc240f338.png)

The lower card is initially hidden and slides up when the user hovers over the upper card.

- [ ] Create TS Component
- [ ] Add documentation for the component

**Comment by rohinivsenthil** [comment]
Hey! I'd like to pick this up.

**Comment by shubhamzanwar** [comment]
Thanks for your interest @rohinivsenthil 
You could check out the [contributing guide](https://github.com/shubhamzanwar/flippie/blob/master/.github/CONTRIBUTING.md) and raise a PR

Happy to help if you need me somewhere :)
